Extra option to mount demo datasets into engine container.
alibaba/GraphScope pull request #1012
Opened 2021-11-17 03:32 UTC by siyuan0322

This PR will allow user to mount the demo dataset bucket into engine container in k8s mode.

2021-11-17 03:39 UTC, yecol requested changes

2021-11-17 03:39 UTC, yecol commented on README.md
> +sess = graphscope.session(with_demo_dataset=True)
mount_dataset="/dataset"

2021-11-17 03:39 UTC, yecol commented on README.md
> +For convenience, we provide several demo datasets, and an option `with_demo_dataset` to mount the dataset in the graphscope cluster. The datasets will located in `/dataset`.
... The datasets will mount to `~/dataset` in the pods as default, or you can assign any other location. If you want to use your own data on k8s cluster, please refer to [this](#).

2021-11-17 03:39 UTC, yecol commented on README.md
> +<details>
remove L258-268 to docs.

2021-11-17 08:29 UTC, siyuan0322 commented
Renamed parameters according to comments and also updated the README.md and README-zh.md

2021-11-17 16:22 UTC, sighingnow approved these changes

2021-11-18 11:35 UTC, lidongze0629 approved these changes

2021-11-22 03:14 UTC, merged