Fixes failure of nightly CI
alibaba/GraphScope pull request #1067
Opened 2021-11-29 04:13 UTC by lidongze0629

## What do these changes do?

## Related issue number

Fixes

2021-11-29 07:44 UTC, yecol approved these changes

2021-11-29 10:54 UTC, sighingnow requested changes

2021-11-29 10:54 UTC, sighingnow commented on python/setup.py
> +    include_dirs.append("/usr/local")
Include dir is `/usr/local/include`, rather than `/usr/local`.

2021-11-30 02:08 UTC, sighingnow approved these changes

2021-11-30 03:00 UTC, merged