Revise built-in clustering and replace forward with built-in
alibaba/GraphScope pull request #1255
Opened 2022-01-06 12:23 UTC by acezen

## What do these changes do?

## Related issue number

Fixes

2022-01-07 02:18 UTC, yecol requested changes

2022-01-07 02:18 UTC, yecol commented on python/graphscope/nx/algorithms/tests/builtin/test_cluster.py
> +    assert nx.builtin.average_clustering(G, count_zeros=True) in (
https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertAlmostEqual

2022-01-07 11:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/GraphScope?pullRequest=1255) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/GraphScope?pullRequest=1255) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/GraphScope?pullRequest=1255) it.</sub>

2022-01-08 03:49 UTC, sighingnow approved these changes

2022-01-10 06:05 UTC, yecol approved these changes

2022-01-10 06:19 UTC, merged

2022-01-10 12:54 UTC, sighingnow commented
I'm curious about why the CI was green before merge but failed on main...