[WIP] Add data caching for networkx to improve the graph report performance
alibaba/GraphScope pull request #1369
Opened 2022-03-14 01:44 UTC by acezen

## What do these changes do?

## Related issue number

Fixes

2022-04-11 03:51 UTC, sighingnow requested changes
I'm a bit unsure about if we need to introduce the msgpack dependency here, as we already have json as the serialization protocol, introducing a another one looks a bit redundant.

I think the issue here is json's inability to differ from tuple and list. But I cannot see how msgpack resolves that, as in `pack()` method in `msgpack_utils.h` I haven't found cases that related to tuple.

2022-04-11 03:51 UTC, sighingnow commented on python/graphscope/nx/classes/cache.py
> +        node_array = msgpack.load(fp, use_list=False)
msgpack could be `None`, as you have

```python
try:
    import msgpack
except ImportError:
    msgpack = None
import simdjson
```

2022-04-11 04:10 UTC, acezen commented
> 

`msgpack` can parse array into `tuple` fast, not only list in json, that's what we need since list can't be key of hash map.  And `msgpack` unpack is faster than `simdjson` load.
https://github.com/msgpack/msgpack-python#how-to-use

2022-04-11 04:10 UTC, acezen commented on python/graphscope/nx/classes/cache.py
> +        node_array = msgpack.load(fp, use_list=False)
thanks, I'll fix it

2022-04-11 05:47 UTC, sighingnow approved these changes
> in the future, we can replace json with msgpack protocol somehow.
https://github.com/msgpack/msgpack-python#how-to-use

As long as we have some (micro) benchmarks that could show msgpack is faster than json (both in the C++ side and Python side).

2022-04-11 06:04 UTC, lidongze0629 approved these changes

2022-04-12 02:02 UTC, sighingnow approved these changes

2022-04-12 02:17 UTC, sighingnow approved these changes

2022-04-12 02:57 UTC, merged