Correctly handle the lifecycle of graph
alibaba/GraphScope pull request #1460
Opened 2022-04-15 02:33 UTC by siyuan0322

- Use del rather than unload
- Projected graph now hold a reference to the base graph

Fixes #1394

2022-04-15 03:02 UTC, lidongze0629 approved these changes

2022-04-15 03:16 UTC, sighingnow requested changes
And, I suggest using `del` instead of private `_unload()` in affected test cases.

2022-04-15 03:16 UTC, sighingnow commented on python/graphscope/framework/graph.py
> -        raise NotImplementedError
Please keep the `unload()` API, and raising a warning to tell users about the deprecation, like

```
warnings.warn("The Graph.unload() method has been deprecated, please using the `del` operator instead, e.g., `del graph`", DeprecationWarning)
```

2022-04-15 03:24 UTC, siyuan0322 commented
> And, I suggest using `del` instead of private `_unload()` in affected test cases.

These remaining `_unload()` is for lazy... you must have a return value for session to run...

2022-04-15 03:39 UTC, sighingnow commented
> > And, I suggest using `del` instead of private `_unload()` in affected test cases.
> 
> These remaining `_unload()` is for lazy... you must have a return value for session to run...

We could `sess.eval(g._unload())` in `_del` in both cases.

2022-04-18 02:15 UTC, sighingnow approved these changes

2022-04-18 07:37 UTC, merged