[WIP] Add coding style guide doc
alibaba/GraphScope pull request #2542
Opened 2023-03-21 04:43 UTC by acezen

## What do these changes do?

## Related issue number

Fixes

2023-03-21 05:19 UTC, sighingnow commented
Can you given some instructions to tell how to format corresponding code to those styles, e.g., `make gsa_clformat`, respectively.

2023-03-23 09:53 UTC, yecol commented on docs/development/code_style_guide.md
> +[1]: https://google.github.io/styleguide/cppguide.html
make all the links inline and clickable.

2023-03-23 09:57 UTC, yecol requested changes

2023-03-23 09:57 UTC, yecol commented on docs/development/code_style_guide.md
> +## Conclusion
No need for conclusion.

2023-03-23 09:57 UTC, yecol commented on docs/development/code_style_guide.md
> +We follow a [custom style][3] for coding standards in Rust.
what?

2023-03-23 09:57 UTC, yecol commented on docs/development/how_to_contribute.md
> +If you find a bug in GraphAr, first make sure that you are testing against the [latest version of GraphScope](https://github.com/alibaba/GraphScope/tree/main),
GraphAr -> GraphScope.

2023-03-23 09:57 UTC, yecol commented on docs/development/how_to_contribute.md
> +Documentation improvements are also a great way to gain some experience with our submission and review process, discussed below, without requiring a lot of local development environment setup. In fac
in the Github web? no, we have a more straight-forward way.  we have the edit button on the docs page.

2023-03-23 09:57 UTC, yecol commented on docs/development/how_to_contribute.md
> +If you find yourself wishing for a feature that doesn't exist in GraphScope, you are probably not alone.
... Maybe proofread in chatgpt. or Cursor.

2023-04-07 06:04 UTC, yecol approved these changes

2023-04-07 08:50 UTC, merged