support load full graph in dynamic_fragment
alibaba/GraphScope pull request #325
Opened 2021-05-18 10:03 UTC by acezen

## What do these changes do?
support load full graph in dynamic fragment.
Users need to init graph by

```python
G = nx.Graph(full_stored=True)
```

## Related issue number
#317

2021-05-19 09:00 UTC, yecol commented
maybe revise the parameter name.
```
G = nx.Graph(duplicated_load=True)
```

2021-05-24 02:19 UTC, sighingnow commented on analytical_engine/core/vertex_map/dynamic_fragment_vertex_map.h
> +    }
Otherwise we don't need a vertexmap?

2021-05-24 02:19 UTC, sighingnow approved these changes

2021-05-24 03:00 UTC, pwrliang requested changes

2021-05-24 03:07 UTC, acezen commented on analytical_engine/core/vertex_map/dynamic_fragment_vertex_map.h
> +  void Init() override { Base::Init(); }
good suggestion, that would be more clear, I would fix this.

2021-05-24 03:25 UTC, acezen commented on analytical_engine/core/vertex_map/dynamic_fragment_vertex_map.h
> +  void Init() override { Base::Init(); }
fixed.

2021-05-24 05:51 UTC, pwrliang approved these changes

2021-05-24 06:34 UTC, yecol commented
according to our discussion: 
```python
# by default, duplicated load
G = nx.Graph()

# or load a fragment, rather than a whole graph.
G = nx.Graph(distributed_load=True)
```

2021-05-28 02:14 UTC, acezen commented
hi, @yecol @sighingnow @pwrliang the refactoring of duplicated load of DynamicFragment is done. the pr needs you to review again. Thanks a lot.

2021-05-28 02:21 UTC, yecol approved these changes

2021-05-28 03:22 UTC, sighingnow approved these changes

2021-05-28 06:10 UTC, merged