Add FAQ doc
alibaba/GraphScope pull request #346
Opened 2021-05-25 10:30 UTC by lidongze0629

## What do these changes do?

## Related issue number

Fixes

2021-05-25 10:53 UTC, yecol requested changes

2021-05-25 10:53 UTC, yecol commented on docs/zh/frequently_asked_questions.rst
> +    GraphScope并不是一个图数据库，其无法提供图上的一些事物性操作。相反，GraphScope使用“immutable”的分布式内存存储以支持快速的图查询和图分析操作。
...事务操作。GraphScope 将图分布式地载入内存作为不可变数据，来支持对该图的查询和分析操作。

2021-05-25 10:53 UTC, yecol commented on docs/zh/frequently_asked_questions.rst
> +    您可以通过 `issue的方式 <https://github.com/alibaba/GraphScope/issues/new/choose>`_ 或 `在讨论区 <https://github.com/alibaba/GraphScope/discussions>`_ 提出你的问题，同时，您也可以使用 `Slack <http://slack.graphscope.io>`_ 或
dingtalk link:    https://h5.dingtalk.com/circle/healthCheckin.html?dtaction=os&corpId=ding82073ee2a22b2f86748126f6422b5d02&109d1=d3892&cbdbhh=qwertyuiop

2021-05-25 10:53 UTC, yecol commented on README.md
> +[![LICENSE](https://img.shields.io/github/license/etcd-io/etcd.svg?style=flat-square)](https://github.com/etcd-io/etcd/blob/main/LICENSE)
???

2021-05-25 10:53 UTC, yecol commented on README.md
>  [![GraphScope CI](https://github.com/alibaba/GraphScope/workflows/GraphScope%20CI/badge.svg)](https://github.com/alibaba/GraphScope/actions?workflow=GraphScope+CI)
maybe sort the badges:
line-1: CI, coverage, try, helm
line-2: docs...

2021-05-25 10:55 UTC, yecol commented on docs/zh/frequently_asked_questions.rst
> +    然而，由于Graphscope依赖众多第三方的库和项目，为了节省你的时间，我们建议基于我们提供的镜像构建并运行GraphScope，如果你没有一个运行的Kubernetes集群，可以使用官方提供的 `kind <https://kind.sigs.k8s.io/>`_ 来快速搭建一个集群。
来快速搭建一个集群。->  在本地快速搭建一个虚拟集群。

2021-05-26 08:45 UTC, sighingnow approved these changes
LGTM, with some minor comments.

2021-05-26 08:45 UTC, sighingnow commented on docs/zh/frequently_asked_questions.rst
> +*5. GraphScope是图数据库嘛？*
嘛 -> 吗

2021-05-26 08:45 UTC, sighingnow commented on docs/zh/frequently_asked_questions.rst
> +*6. GraphScope在Gremlin上的支持性如何？*
支持性 -> 兼容性

2021-05-26 08:45 UTC, sighingnow commented on docs/zh/frequently_asked_questions.rst
> +下面是用户在使用GraphScope过程中遇到的常见问题，如果你的问题仍无法解决，可通过 `issue的方式 <https://github.com/alibaba/GraphScope/issues/new/choose>`_ 或 `在讨论区 <https://github.com/alibaba/GraphScope/discussions>`_ 与我们联系。
下面是用户在使用GraphScope过程中遇到的常见问题，如果你的问题仍无法解决 -> 我们收集了用户使用GraphScope过程中的常见问题，如果在下面的列表中仍然无法找到您遇到的问题的答案

2021-05-26 08:45 UTC, sighingnow commented on docs/frequently_asked_questions.rst
> +    However, GraphScope depends on many third-party libraries and projects. To make our life easier, we suggest you build and run GraphScope on k8s with our provided dev-image and release-image. If y
”To make our life easier“ -> To make the setup process easier

2021-05-26 08:45 UTC, sighingnow commented on docs/frequently_asked_questions.rst
> +    However, GraphScope depends on many third-party libraries and projects. To make our life easier, we suggest you build and run GraphScope on k8s with our provided dev-image and release-image. If y
an k8s managed cluster -> a kubernetes cluster.

2021-05-26 08:45 UTC, sighingnow commented on docs/frequently_asked_questions.rst
> +    However, GraphScope depends on many third-party libraries and projects. To make our life easier, we suggest you build and run GraphScope on k8s with our provided dev-image and release-image. If y
to use the images -> to try graphscope.

2021-05-26 08:45 UTC, sighingnow commented on docs/frequently_asked_questions.rst
> +    By default, GraphScope is mostly running in a silent mode following the style of Python.
mostly -> usually

2021-05-26 08:45 UTC, sighingnow commented on docs/frequently_asked_questions.rst
> +    By default, GraphScope is mostly running in a silent mode following the style of Python.
the style of Python -> the convention of Python applications.

2021-05-26 08:45 UTC, sighingnow commented on docs/frequently_asked_questions.rst
> +    If GraphScope seems get stuck, the possible reasons:
Seem to get...

the possible cause might be

2021-05-26 08:45 UTC, sighingnow commented on docs/frequently_asked_questions.rst
> +    - In the analysis stage with a UDF/built-in algorithm, it takes time to compile/distribute the algorithm over the loaded graph.
When running a user-defined or built-in analytical algorithm

2021-05-27 06:37 UTC, yecol approved these changes

2021-05-27 06:38 UTC, yecol approved these changes

2021-05-27 06:38 UTC, yecol approved these changes

2021-05-27 07:44 UTC, merged