combine prepare_env script into one
alibaba/GraphScope pull request #38
Opened 2020-12-23 11:11 UTC by acezen

## What do these changes do?
combine the prepare_env.sh and prepare_env_wsl.sh into one

## Related issue number

Fixes #33

2020-12-23 11:12 UTC, acezen commented
cc/ @yecol @sighingnow please review and give some comments.

2020-12-23 11:27 UTC, sighingnow approved these changes
LGTM, just a little concern about `WSL_DISTRO_NAME` or `IS_WSL`? Are they guaranteed to exist under WSL2 environment?

2020-12-23 11:33 UTC, siyuan0322 commented on scripts/prepare_env.sh
> +  if [[ ! -z "$IS_WSL" && ! -z "$WSL_DISTRO_NAME" ]]; then
Nits: Consider extract the the common part `! -z "$IS_WSL" && ! -z "$WSL_DISTRO_NAME"` into one boolean variable so we don't need to evaluate it multiple times, and will be more clear.
And please add curly braces around `IS_WSL` and `WSL_DISTRO_NAME` like the other variables do.

2020-12-23 12:28 UTC, acezen commented
> LGTM, just a little concern about `WSL_DISTRO_NAME` or `IS_WSL`? Are they guaranteed to exist under WSL2 environment?

there is a issue in WSL that suggest to use the env to check is in WSL or not. https://github.com/microsoft/WSL/issues/4555#issuecomment-700213318

2020-12-23 15:32 UTC, sighingnow approved these changes

2020-12-23 15:32 UTC, sighingnow commented on scripts/prepare_env.sh
> +  if [[ ! -z ${IS_WSL} && ! -z ${WSL_DISTRO_NAME} ]]; then
I think you need `"${IS_WSL}"` rather than `{IS_WSL}`. As well for `WSL_DISTRO_NAME`.

Otherwise LGTM.

2020-12-24 02:31 UTC, sighingnow requested changes
Please update README.md which refers `prepare_env_wsl.sh` (and maybe tutorial, references, etc.)

![image](https://user-images.githubusercontent.com/7144772/103052005-0a68fa00-45d3-11eb-93a1-361c35859558.png)

2020-12-24 06:40 UTC, yecol requested changes
I suggest the script could be more verbose.
- tell user what is doing.
- give a summary at the end of the entire process. 

e.g.,
```
minikube VERSION installed.
# or 
kind VERSION installed.
dockerd started.
...
```

2020-12-24 06:40 UTC, yecol commented on scripts/prepare_env.sh
> +  sudo docker pull registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:latest || true
echo "pulling graphscope images...."

2020-12-24 08:13 UTC, acezen commented
> I suggest the script could be more verbose.
> 
> * tell user what is doing.
> * give a summary at the end of the entire process.
> 
> e.g.,
> 
> ```
> minikube VERSION installed.
> # or 
> kind VERSION installed.
> dockerd started.
> ...
> ```
 already add some verbose log and a summary to script, please review again

2020-12-24 08:14 UTC, sighingnow approved these changes

2020-12-25 02:42 UTC, yecol approved these changes

2020-12-25 02:42 UTC, merged