[WIP]feat : Improve the robustness of code
alibaba/GraphScope pull request #4170
Opened 2024-08-21 06:12 UTC by FLYLX

## What do these changes do?

Increase code robustness by making try-catch snippets of code that may cause resource leaks, and fixing some details.

## Related issue number

Fixes

2024-08-21 06:40 UTC, lidongze0629 commented on README.md
> +paper_features += ["kcore", "tc"]
paper_features.extend(["kcore", "tc"])

2024-08-21 06:44 UTC, lidongze0629 commented on flex/interactive/sdk/python/gs_interactive/client/session.py
> +    #Get the schema of a specified graph.
Follow the existing comment style.

https://github.com/alibaba/GraphScope/blob/main/python/graphscope/analytical/app/average_degree_connectivity.py#L32

2024-08-21 06:55 UTC, zhanglei1949 requested changes

2024-08-21 06:55 UTC, zhanglei1949 commented on analytical_engine/java/grape-jdk/src/main/java/com/alibaba/graphscope/serialization/FFIByteVectorOutputStream.java
> +        vector.clear();
Should not clear the vector, which will clear the allocated memory.

2024-08-21 06:55 UTC, zhanglei1949 commented on analytical_engine/java/grape-graphx/src/main/java/com/alibaba/graphscope/utils/PythonInterpreter.java
> +            logger.warn("Interrupted exception when closing python interpreter", e);
I recommend throwing the exception.

2024-08-21 06:55 UTC, zhanglei1949 commented on analytical_engine/java/grape-graphx/src/main/java/com/alibaba/graphscope/utils/PythonInterpreter.java
> +            ProcessBuilder builder = new ProcessBuilder("/usr/bin/env", "python3", "-i");
Throwing the exception may be better.

2024-08-21 07:46 UTC, acezen commented on python/graphscope/client/session.py
> +        except ModuleNotFoundError:
no need to add `try `here, since the ModuleNotFoundError is the error we want to raise.

2024-08-23 02:23 UTC, lidongze0629 approved these changes
LGTM

2024-08-23 02:23 UTC, zhanglei1949 approved these changes
LGTM

2024-08-23 02:30 UTC, merged