add app kshell
alibaba/GraphScope pull request #66
Opened 2021-01-05 09:34 UTC by varinic

## What do these changes do?

Add kshell application to GraphScope analytical_engine.

## Related issue number

no issues fixed

2021-01-05 09:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/GraphScope?pullRequest=66) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/GraphScope?pullRequest=66) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/GraphScope?pullRequest=66) it.</sub>

2021-01-08 05:21 UTC, sighingnow commented
Hi @varinic, thanks for contributing the algorithm. To get this pull request landed, please following our developer guide and error message in CI to fixed the code format of your patch.

2021-01-08 05:24 UTC, sighingnow commented
THIMC: pull request https://github.com/7br/gstest/pull/34 needs to be merged first.

2021-01-08 11:22 UTC, sighingnow approved these changes

2021-01-08 12:29 UTC, lidongze0629 requested changes

2021-01-08 12:29 UTC, lidongze0629 commented on python/graphscope/analytical/app/k_shell.py
> +    return AppAssets(algo="kshell")(graph, k=k)
Builtin-app doesn't need `kwargs` params.
```python
k = int(k)
return AppAssets(algo="kshell")(graph, k)
```

2021-01-11 02:43 UTC, yecol commented
please revise according to dongze's comment and make the CI pass.

2021-01-12 03:10 UTC, yecol approved these changes

2021-01-12 03:11 UTC, lidongze0629 approved these changes

2021-01-12 03:27 UTC, merged