Try to read namespace from kube config when missing k8s_namesapce param
alibaba/GraphScope pull request #95
Opened 2021-01-18 09:33 UTC by lidongze0629

## What do these changes do?

## Related issue number

Fixes #88

2021-01-18 09:44 UTC, sighingnow approved these changes

2021-01-18 10:50 UTC, sighingnow requested changes
@lidongze0629 Please also update the docstring for "namespace":

https://github.com/alibaba/GraphScope/blob/main/python/graphscope/client/session.py#L173

2021-01-18 11:07 UTC, yecol approved these changes

2021-01-20 05:57 UTC, sighingnow approved these changes

2021-01-20 05:58 UTC, merged