check os compatibility and dependencies_version in prepare_env.sh
alibaba/GraphScope pull request #99
Opened 2021-01-22 02:39 UTC by acezen

## What do these changes do?

check os compatibility and dependencies_version in prepare_env.sh to improve "Getting Started" experience

## Related issue number

Fixes #93

2021-01-22 02:43 UTC, acezen commented
cc/  @yecol @sighingnow @wenyuanyu

2021-01-22 03:12 UTC, sighingnow approved these changes
LGTM.

Not part of this task, but I'm wondering if we suggest users kind rather than minikube on Linux and MacOS as well. Test is needed, though. (not in high pri).

2021-01-22 03:47 UTC, yecol requested changes
You may also want to revise the file in `/docs`, for  https://graphscope.io/docs/installation.html

2021-01-22 03:47 UTC, yecol commented on README.md
> +For Ubuntu/CentOs/WSL2, we provide a script to install the above dependencies and prepare the environment.
CentOS

2021-01-22 08:18 UTC, wenyuanyu commented
Maybe also checking the platform's version? like Ubuntu 14, 16, 18?

2021-01-25 04:00 UTC, yecol requested changes

2021-01-25 05:11 UTC, acezen commented
> LGTM.
> 
> Not part of this task, but I'm wondering if we suggest users kind rather than minikube on Linux and MacOS as well. Test is needed, though. (not in high pri).

thanks for the suggestion. this script can include MacOS prepare environment though kind i think, i will add this feature in next related pr after test.

2021-01-26 02:08 UTC, yecol approved these changes

2021-01-26 02:12 UTC, merged